% Wu siyuan Meudon 
% add cassini orbital data to the x axis
% input
%% required
%xaxis: time axis data

%% optional
% empherm_data: Cassini orbital data generated by get_emph_data3
% ifXTickLabel: 1: add Xticklabel (require the input empherm_data), 0: do nothing

% output:
% x_tick_loca: calculate the full hour/halfhour/min using xaxis data and
% output the location
%%
function xtick_loca=add_ephm(xaxis,varargin)
%empherm_data,ifaddTickLabel

p=inputParser;
p.addParameter('empherm_data',[]);
p.addParameter('ifXTickLabel',0);
p.parse(varargin{:});

if length(xaxis)<10
    xtick_loca=[];
    return
end
    xaxis2=xaxis;
if xaxis(end)<datenum('2004-01-01')
    xaxis=xaxis+datenum('1997-01-01 00:00:00')-1;
end

t_vec=datevec(xaxis);

if t_vec(1,5)==59
    t_vec(1,:)=datevec(xaxis(1)+1/1440);
end
if t_vec(end,5)==59
    t_vec(end,:)=datevec(xaxis(end)+1/1440);
end

hours=round((datenum(t_vec(end,:))-datenum(t_vec(1,:)))*24);

loca_fullHour=find(t_vec(:,5)==0);
loca_loca_fullHour=[1;1+find(diff(loca_fullHour)~=1)];
if ~isempty(loca_fullHour)
fullHour=loca_fullHour(loca_loca_fullHour);
else
    fullHour=[];
end
loca_tick=fullHour;

halfHour=[];
if length(fullHour)+1<3
loca_halfHour=find(t_vec(:,5)==30|t_vec(:,5)==0);
loca_loca_halfHour=[1;1+find(diff(loca_halfHour)~=1)];

halfHour=loca_halfHour(loca_loca_halfHour);

loca_tick=halfHour;
end

loca_10min=[];
min10=[];
if ~isempty(halfHour)&length(halfHour)+1<3
loca_10min=find(t_vec(:,5)==10|t_vec(:,5)==20|t_vec(:,5)==30|t_vec(:,5)==40|t_vec(:,5)==50|t_vec(:,5)==0);
loca_loca_10min=[1;1+find(diff(loca_10min)~=1)];
min10=loca_10min(loca_loca_10min);
loca_tick=min10;
end

if ~isempty(loca_10min)&length(min10)+1<3
    [~,unique_min]=unique(t_vec(:,5),'first');
    unique_min=t_vec(sort(unique_min),5);
    
    loca_1min=[];
    for i=1:length(unique(t_vec(:,5)))
        loca_1min=[loca_1min;min(find(t_vec(:,5)==unique_min(i)))];
    end
        
loca_loca_1min=[1;1+find(diff(loca_1min)~=1)];
min1=loca_1min(loca_loca_1min);
loca_tick=min1;
end

if isempty(loca_tick)
       xtick_loca=[];
    return
end

if length(loca_tick)>=3&length(loca_tick)<8
    loca_tick_final=loca_tick;
elseif length(loca_tick)<3|length(loca_tick)>=8
    
%     if (length(loca_tick)-1)==hours&(mod(hours,2)~=0)
%         loca_tick_final=loca_tick(round(linspace(1,length(loca_tick),6)));
%     elseif (length(loca_tick)-1)==hours&(mod(hours,2)==0)
%         loca_tick_final=loca_tick(round(linspace(1,length(loca_tick),7)));
%     else
%     loca_tick_final=loca_tick;
%     end

 if (length(loca_tick)-1)==hours&(mod(hours,2)~=0)
        loca_tick_final=round(linspace(1,loca_tick(end),4));
    elseif (length(loca_tick)-1)==hours&(mod(hours,2)==0)
        loca_tick_final=loca_tick(round(linspace(1,length(loca_tick),5)));
    else
    loca_tick_final=loca_tick;
    end

end


if p.Results.ifXTickLabel==1

for i=1:length(loca_tick_final)
xticklabel{i}=strcat(num2str(t_vec(loca_tick_final(i),2)),'-',num2str(t_vec(loca_tick_final(i),3)),...
    ',',num2str(t_vec(loca_tick_final(i),4),'%02.f'),':',...
    num2str(t_vec(loca_tick_final(i),5),'%02.f'));
end
xticklabel{1}=strcat('UT:',32,xticklabel{1});

%set(gca,'Xtick',xaxis(loca_tick_final),'XTickLabel',xticklabel,'fontsize',9)

%%

Xtick_t_regi_emphem=ceil(loca_tick_final/length(t_vec)*size(p.Results.empherm_data,1));
Xtick_t_label_LT=cellstr(num2str(roundn(p.Results.empherm_data(Xtick_t_regi_emphem,11),-2),'%.2f'));
Xtick_t_label_Lat=cellstr(num2str(roundn(p.Results.empherm_data(Xtick_t_regi_emphem,9),-2),'%.2f'));
Xtick_t_label_Lshell=cellstr(num2str(roundn(p.Results.empherm_data(Xtick_t_regi_emphem,10),-2),'%.2f'));
Xtick_t_label_Rs=cellstr(num2str(roundn(p.Results.empherm_data(Xtick_t_regi_emphem,13),-2),'%.2f'));

Xtick_t_label_LT=cellstr(num2str(roundn(p.Results.empherm_data(Xtick_t_regi_emphem,11),-2),'%.2f'));
Xtick_t_label_Lat=cellstr(num2str(roundn(p.Results.empherm_data(Xtick_t_regi_emphem,9),-2),'%.2f'));
Xtick_t_label_Lshell=cellstr(num2str(roundn(p.Results.empherm_data(Xtick_t_regi_emphem,10),-2),'%.2f'));
Xtick_t_label_Rs=cellstr(num2str(roundn(p.Results.empherm_data(Xtick_t_regi_emphem,13),-2),'%.2f'));
Xtick_t_label_LT{1}=strcat('LT:',32,Xtick_t_label_LT{1});
Xtick_t_label_Lat{1}=strcat('Lat:',32,Xtick_t_label_Lat{1});
Xtick_t_label_Lshell{1}=strcat('L:',32,Xtick_t_label_Lshell{1});
Xtick_t_label_Rs{1}=strcat('Rs:',32,Xtick_t_label_Rs{1});

labelArray = [xticklabel;Xtick_t_label_LT';Xtick_t_label_Lat';Xtick_t_label_Lshell';Xtick_t_label_Rs']; 
tickLabels = strtrim(sprintf('%s\\newline%s\\newline%s\\newline%s\\newline%s\n', labelArray{:}));
NoChangePos=get(gca,'Position');
NoChangCbar=get(ancestor(gca, 'axes'), 'Colorbar');
NoChangCbarPos=NoChangCbar.Position

if length(unique(xaxis2(loca_tick_final)))~=length(xaxis2(loca_tick_final))
   xaxis3=unique(xaxis2(loca_tick_final));
else
    xaxis3=xaxis2(loca_tick_final);
end
set(gca,'Xtick',xaxis3,'XTicklabel',tickLabels);
set(gca,'Position',NoChangePos);
NoChangCbar=get(ancestor(gca, 'axes'), 'Colorbar')
set(NoChangCbar,'Position',NoChangCbarPos);
  xtick_loca=xaxis(loca_tick_final); 
else
  xtick_loca=xaxis(loca_tick_final)-datenum('1997-01-01 00:00:00')+1;  
  if length(unique(xtick_loca))~=length(xtick_loca)
    xtick_loca=unique(xtick_loca);
end
end


    
end


